Complete exercises on arrays
alexSmkh/study pull request #1
Opened 2021-11-12 16:10 UTC by alexSmkh

2021-11-13 09:55 UTC, Yoffic requested changes

2021-11-13 09:55 UTC, Yoffic commented on test/exercise/arrays/solution.rb
> +        max_value = array.max
В рамках задания нельзя использовать стандартные функции для поиска максимума

2021-11-13 09:55 UTC, Yoffic commented on test/exercise/arrays/solution.rb
> +        while right_index >= left_index
Двоичный поиск нужно реализовать, используя рекурсию.

2021-11-17 08:34 UTC, moklidia approved these changes

2021-11-17 10:07 UTC, merged